# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef8efab16fecd66a77ccab48874037b9ef5a76e73d743e5e3ddd35d4f1863f0e5e97913b6c28020138c3b8a6a4e455948379d8f40a57e3737890be95701ede0f

test:
  secret_key_base: 5437536eb2b89ef4c120ffb198dacd33930c9769261cb44a0dd3d0ca14b8ff96a0453b88290890484292dd9c30ba4772023ee39c2205f50c7844eadf3abcad99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
